{
    'name': 'Odoo SaaS Master',
    'version': '18.0.0.13',
    'author': 'SkyERP',
    'category': 'Odoo SaaS',
    'sequence': 15,
    'summary': 'Manage Odoo instance based on Docker',
    'description': """
    """,
    'depends': ['website_sale', 'sale_management'],
    'external_dependencies': {
        'python': ['paramiko'],
    },
    'data': [
        'data/saas_odoo_version_data.xml',
        'data/saas_odoo_version_config_section_data.xml',
        'data/config_14_data.xml',
        'data/config_15_data.xml',
        'data/config_16_data.xml',
        'data/config_17_data.xml',
        'data/config_18_data.xml',
        'data/config_19_data.xml',
        'data/saas_psql_version_data.xml',
        'data/ir_cron_data.xml',
        'data/ir_config_parameter_data.xml',
        'data/template_email_data.xml',
        'data/uom_data.xml',
        'data/saas_instance_tag_data.xml',
        'data/product_public_category_data.xml',
        'data/product_product_data.xml',
        'data/website_menu_data.xml',
        'data/saas_resource_package_data.xml',
        'data/saas_resource_package_line_data.xml',
        'security/odoo_saas_security.xml',
        'security/ir.model.access.csv',
        'wizard/res_config_settings_views.xml',
        'wizard/saas_odoo_instance_redeploy_wizard_views.xml',
        'wizard/saas_odoo_instance_upgrade_module_wizard_views.xml',
        'wizard/odoo_instance_cancel_wizard_views.xml',
        'wizard/saas_odoo_instance_backup_restore_wizard_views.xml',
        'wizard/saas_odoo_instance_duplicate_wizard_views.xml',
        'views/saas_menu_views.xml',
        'views/saas_ssh_keypair_views.xml',
        'views/saas_odoo_version_views.xml',
        'views/saas_odoo_version_config_views.xml',
        'views/saas_psql_version_views.xml',
        'views/saas_pserver_views.xml',
        'views/saas_nginx_server_views.xml',
        'views/saas_based_domain_views.xml',
        'views/saas_blocked_domain_views.xml',
        'views/saas_odoo_server_views.xml',
        'views/saas_odoo_instance_views.xml',
        'views/saas_odoo_instance_port_views.xml',
        'views/saas_odoo_instance_config_views.xml',
        'views/saas_odoo_instance_docker_container_views.xml',
        'views/saas_odoo_instance_docker_compose_volume_views.xml',
        'views/saas_odoo_instance_domain_name_views.xml',
        'views/saas_odoo_instance_backup_views.xml',
        'views/saas_odoo_instance_custom_addon_views.xml',
        'views/saas_odoo_instance_installed_app_views.xml',
        'views/res_partner_views.xml',
        'views/portal_template_views.xml',
        'views/product_template_views.xml',
        'views/product_pricelist_view.xml',
        'views/sale_order_views.xml',
        'views/pricing.xml',
        'views/account_move_views.xml',
        'views/saas_instance_tag_views.xml',
        'views/saas_docker_image_views.xml',
        'views/saas_resource_package_views.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            's_odoo_saas_master/static/src/components/**/*',
            's_odoo_saas_master/static/src/js/**/*',
            's_odoo_saas_master/static/src/scss/loading.scss',
            's_odoo_saas_master/static/src/scss/saas_pricing.scss',
            's_odoo_saas_master/static/src/scss/checkout_form.scss',
            's_odoo_saas_master/static/src/scss/myodoo_portal.scss',
        ],
        'web.assets_backend': [
            's_odoo_saas_master/static/src/backend/saas_backup_restore_progress_field.js',
            's_odoo_saas_master/static/src/backend/saas_backup_restore_progress_field.xml',
        ],
    },
    'post_init_hook': '_price_list_post_init_hook',
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'license': 'OPL-1',
    'price': 699,
    'currency': 'EUR',
}
